<a href="https://colab.research.google.com/github/Dhawaldwivedi/Python-Basics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# python librares
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy

- faster processing
- less memory consumption
- functionality
- integration with other libraries


In [1]:
#numpy
!pip install numpy

In [2]:
import numpy as np

In [3]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim #for dimension of array

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
# zero array
z = np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# ones
o = np.ones((3,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# random function
round(np.random.random(),3)

0.026

In [18]:
np.random.random((2,2))

array([[0.1364045 , 0.80065413],
       [0.59930003, 0.36118153]])

In [23]:
np.random.randint(1,10000)

2046

In [29]:
np.random.randint(1,6)

5

In [30]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.arange(1,11,8) # stepsize

array([1, 9])

In [37]:
np.linspace(1,11,8) # number of elements

array([ 1.        ,  2.42857143,  3.85714286,  5.28571429,  6.71428571,
        8.14285714,  9.57142857, 11.        ])

In [38]:
# reshape function
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.reshape(z,(5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# flatten
z.flatten() # converts into 1 dimension

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
p = np.random.random((3,5))
p

array([[0.0662072 , 0.21148471, 0.24183153, 0.43833535, 0.06368892],
       [0.5249471 , 0.07896772, 0.5897504 , 0.61896672, 0.42087372],
       [0.12725814, 0.90857667, 0.52772128, 0.86571376, 0.81656211]])

In [47]:
np.reshape(p,(5,3))

array([[0.0662072 , 0.21148471, 0.24183153],
       [0.43833535, 0.06368892, 0.5249471 ],
       [0.07896772, 0.5897504 , 0.61896672],
       [0.42087372, 0.12725814, 0.90857667],
       [0.52772128, 0.86571376, 0.81656211]])

In [50]:
p.flatten()

array([0.0662072 , 0.21148471, 0.24183153, 0.43833535, 0.06368892,
       0.5249471 , 0.07896772, 0.5897504 , 0.61896672, 0.42087372,
       0.12725814, 0.90857667, 0.52772128, 0.86571376, 0.81656211])

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [55]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [56]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
int(arr.max())

9

In [62]:
int(arr.min())

1

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
int(arr.sum())

45

In [65]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [66]:
arr.max(axis=1) # row wise

array([3, 6, 9])

In [68]:
int(arr.trace()) # sum of diagonal elements

15

In [69]:
arr1 =np.array([[2,5,3],
                [4,2,7],
                [3,5,9]])
arr2 =np.array([[1,9,3],
                [2,2,7],
                [7,6,3]])

In [70]:
arr1

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [71]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [72]:
arr3 = arr1+arr2
arr3

array([[ 3, 14,  6],
       [ 6,  4, 14],
       [10, 11, 12]])

In [74]:
# indexing
int(arr3[1,2])

14

In [75]:
arr3[0,:]

array([ 3, 14,  6])

In [76]:
arr3[:,1]

array([14,  4, 11])

In [77]:
arr3[:,:2]

array([[ 3, 14],
       [ 6,  4],
       [10, 11]])

In [78]:
arr3

array([[ 3, 14,  6],
       [ 6,  4, 14],
       [10, 11, 12]])

In [79]:
# sorting
np.sort(arr3)

array([[ 3,  6, 14],
       [ 4,  6, 14],
       [10, 11, 12]])

In [80]:
arr4 = np.sort(arr3,axis=1,kind= 'mergesort')
arr4

array([[ 3,  6, 14],
       [ 4,  6, 14],
       [10, 11, 12]])

In [83]:
arr5 = np.sort(arr3,axis=0)
arr5

array([[ 3,  4,  6],
       [ 6, 11, 12],
       [10, 14, 14]])

In [84]:
# stack - merges 2 arrays
arr1


array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [85]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [88]:
arr3 = np.vstack((arr1,arr2,arr5))
arr3

array([[ 2,  5,  3],
       [ 4,  2,  7],
       [ 3,  5,  9],
       [ 1,  9,  3],
       [ 2,  2,  7],
       [ 7,  6,  3],
       [ 3,  4,  6],
       [ 6, 11, 12],
       [10, 14, 14]])

In [87]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 5, 3, 1, 9, 3],
       [4, 2, 7, 2, 2, 7],
       [3, 5, 9, 7, 6, 3]])

In [89]:
# split functions
np.hsplit(arr4,2)

[array([[2, 5, 3],
        [4, 2, 7],
        [3, 5, 9]]),
 array([[1, 9, 3],
        [2, 2, 7],
        [7, 6, 3]])]

In [90]:
np.vsplit(arr3,3)

[array([[2, 5, 3],
        [4, 2, 7],
        [3, 5, 9]]),
 array([[1, 9, 3],
        [2, 2, 7],
        [7, 6, 3]]),
 array([[ 3,  4,  6],
        [ 6, 11, 12],
        [10, 14, 14]])]

Explore About Z-Score Normalization

 Create a checkerboard pattern (8x8) using NumPy.

Replace negative values in an array with the mean of non-negative values.

Get the indices of the top 3 maximum values in a 1D array.

Given a matrix, subtract the mean of each column from that column.